apiVersion: apps/v1
kind: Deployment
metadata:
   name: order-service
   namespace: production
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: "{{ .Values.global.ecrRegistry }}/order-service:{{ .Values.global.imageTag }}"
        ports:
        - containerPort: {{ .Values.orderService.port }}
        resources:
          requests:
            memory: {{ .Values.orderService.resources.requests.memory }}
            cpu: {{ .Values.orderService.resources.requests.cpu }}
          limits:
            memory: {{ .Values.orderService.resources.limits.memory }}
            cpu: {{ .Values.orderService.resources.limits.cpu }}
      readinessProbe:
        httpGet:
          path: /health
          port: {{ .Values.orderService.port }}
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: {{ .Values.orderService.port }}
        initialDelaySeconds: 30
        periodSeconds: 30  
      envFrom:
      - configMapRef:
          name: platform-config
      env:
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: db-key
            key: host
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: db-key
            key: name
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-key
            key: user            
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-key
            key: password
