global :
  imageTag: "1.0.0"
  ecrRegistry: ""

apiGateway:
  replicaCount: 2
  port: 8000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

userService:
  replicaCount: 2
  port: 5001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

orderService:
  replicaCount: 2
  port: 5002
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

aiService:
  replicaCount: 2
  port: 5003
  model: "llama3.2:1b"
  ollamaUrl: ""   # set via configmap - Ollama runs on EC2 sidecar
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ingress:
  enabled: true
  className: "alb"
  host: "api.microservices.internal"